server:
  port: 8080
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

oneyoung:
  i18n:
    active: en_US
  converter:
    auto-convert: true